-- 코드를 입력하세요
SELECT r1.FOOD_TYPE, r1.REST_ID, r1.REST_NAME, r1.FAVORITES  FROM REST_INFO r1
INNER JOIN (
    SELECT REST_ID, MAX(FAVORITES) MAX, FAVORITES, FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) r2 ON r1.FOOD_TYPE = r2.FOOD_TYPE AND r1.FAVORITES = r2.MAX
ORDER BY r1.FOOD_TYPE DESC