-- 코드를 입력하세요
SELECT 
	MONTH(START_DATE) MONTH,
    CAR_ID,
    COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
	SELECT 
    	CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
    AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING count(*) >= 5
) 
AND START_DATE >= '2022-08-01' 
AND START_DATE < '2022-11-01'
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH ASC, CAR_ID DESC;
