-- 코드를 입력하세요
SELECT 
	ugb.WRITER_ID USER_ID,
    ugu.NICKNAME NICKNAME,
    CONCAT(ugu.CITY, ' ', ugu.STREET_ADDRESS1, ' ', ugu.STREET_ADDRESS2) '전체주소',
    CONCAT(SUBSTRING(ugu.TLNO, 1, 3), '-', SUBSTRING(ugu.TLNO, 4, 4), '-', SUBSTRING(ugu.TLNO, 8)) '전화번호'
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_USER ugu
ON ugb.WRITER_ID = ugu.USER_ID
GROUP BY ugb.WRITER_ID
HAVING COUNT(USER_ID) >= 3
ORDER BY USER_ID DESC;