SELECT
	A.ID ID,
    CASE
    	WHEN (A.SIZE_RANK / A.CNT) <= 0.25 THEN 'CRITICAL'
        WHEN (A.SIZE_RANK / A.CNT) <= 0.5 THEN 'HIGH'
        WHEN (A.SIZE_RANK / A.CNT) <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT 
        ID,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK,
        (SELECT COUNT(*) FROM ECOLI_DATA) AS CNT
    FROM ECOLI_DATA
) AS A
ORDER BY A.ID ASC;