-- 코드를 입력하세요
SELECT 
	ugu.USER_ID USER_ID,
    ugu.NICKNAME NICKNAME,
	sum(ugb.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_USER ugu
ON ugb.WRITER_ID = ugu.USER_ID
WHERE ugb.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;