-- 코드를 입력하세요

# SELECT * FROM FOOD_PRODUCT
# GROUP BY (
    
# )

SELECT DISTINCT(a.CATEGORY), a.PRICE MAX_PRICE, a.PRODUCT_NAME FROM FOOD_PRODUCT a
JOIN (
    SELECT PRODUCT_ID, MAX(PRICE) MAX_PRICE FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) b
ON a.PRICE = b.MAX_PRICE
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC