-- 코드를 입력하세요
SELECT a.CATEGORY, a.PRICE MAX_PRICE, a.PRODUCT_NAME FROM FOOD_PRODUCT a
JOIN (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) b
ON a.PRICE = b.MAX_PRICE
AND a.CATEGORY = b.CATEGORY
ORDER BY MAX_PRICE DESC