SELECT
	YEAR(OS.SALES_DATE) YEAR,
    MONTH(OS.SALES_DATE) MONTH,
    COUNT(DISTINCT OS.USER_ID) PURCHASED_USER,
    ROUND(COUNT(DISTINCT OS.USER_ID) / 
          (SELECT COUNT(USER_ID) FROM USER_INFO
          WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC




