-- 코드를 입력하세요
SELECT bo.CATEGORY CATEGORY, SUM(bos.SALES) TOTAL_SALES
FROM BOOK bo JOIN BOOK_SALES bos
ON bo.BOOK_ID = bos.BOOK_ID
WHERE DATE_FORMAT(bos.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC