-- 코드를 입력하세요
SELECT bo.AUTHOR_ID AUTHOR_ID, au.AUTHOR_NAME AUTHOR_NAME, 
	bo.CATEGORY CATEGORY, sum(sales.SALES * bo.PRICE) TOTAL_SALES
FROM BOOK_SALES sales
INNER JOIN BOOK bo
INNER JOIN AUTHOR au
ON au.AUTHOR_ID = bo.AUTHOR_ID
ON sales.BOOK_ID = bo.BOOK_ID
WHERE date_format(sales.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY bo.AUTHOR_ID, bo.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC