-- 코드를 입력하세요
SELECT pr.PRODUCT_CODE AS PRODUCT_CODE, SUM(off.SALES_AMOUNT) * pr.PRICE AS SALES FROM PRODUCT pr 
JOIN OFFLINE_SALE off
ON pr.PRODUCT_ID = off.PRODUCT_ID
GROUP BY pr.PRODUCT_ID
ORDER BY SALES DESC, pr.PRODUCT_CODE ASC