-- 코드를 입력하세요

SELECT 
    A.HISTORY_ID HISTORY_ID,
    FLOOR(A.DURATION * A.DAILY_FEE * (1 - IF(A.DURATION < 7, 0, CRCDP.DISCOUNT_RATE) / 100)) AS FEE
FROM
(
SELECT 
    CRCRH.HISTORY_ID HISTORY_ID, 
    DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 DURATION,
    CRCC.DAILY_FEE,
    CRCC.CAR_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
INNER JOIN CAR_RENTAL_COMPANY_CAR CRCC
ON CRCRH.CAR_ID = CRCC.CAR_ID
WHERE 1 = 1
AND CRCC.CAR_TYPE = '트럭') A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON CRCDP.CAR_TYPE = A.CAR_TYPE
WHERE 1 = 1
AND 
    CASE
        WHEN A.DURATION >= 90 THEN CRCDP.DURATION_TYPE = "90일 이상"
        WHEN A.DURATION >= 30 THEN CRCDP.DURATION_TYPE = "30일 이상"
        WHEN A.DURATION >- 7 THEN CRCDP.DURATION_TYPE = "7일 이상"
        ELSE 0
    END
ORDER BY FEE DESC, HISTORY_ID DESC