-- 코드를 입력하세요
SELECT 
	ugb.TITLE TITLE, 
    ugb.BOARD_ID BOARD_ID, 
    ugr.REPLY_ID REPLY_ID, 
    ugr.WRITER_ID WRITER_ID,
    ugr.CONTENTS CONTENTS,
    DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_REPLY ugr
ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE DATE_FORMAT(ugb.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY ugr.CREATED_DATE, ugb.TITLE ASC