SELECT 
	DISTINCT 
    DE.ID ID,
    DE.EMAIL EMAIL,
    DE.FIRST_NAME FIRST_NAME,
    DE.LAST_NAME LAST_NAME
FROM DEVELOPERS DE
INNER JOIN SKILLCODES SC
	ON (DE.SKILL_CODE & SC.CODE) > 0
WHERE SC.CATEGORY = 'Front End'
ORDER BY DE.ID ASC;