SELECT CHILD.ID ID, CHILD.GENOTYPE GENOTYPE, PARENT.GENOTYPE PARENT_GENOTYPE FROM ECOLI_DATA CHILD
INNER JOIN ECOLI_DATA PARENT
ON CHILD.PARENT_ID = PARENT.ID
WHERE 1 = 1
AND CHILD.PARENT_ID IS NOT NULL
AND (CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE) = 1
ORDER BY CHILD.ID ASC;