
SELECT B.ID ID, C.FISH_NAME FISH_NAME, B.LENGTH LENGTH FROM FISH_INFO B
INNER JOIN FISH_NAME_INFO C
ON B.FISH_TYPE = C.FISH_TYPE
WHERE B.LENGTH 
IN (
	SELECT MAX(A.LENGTH) FROM FISH_INFO A
    WHERE A.FISH_TYPE = B.FISH_TYPE
	GROUP BY A.FISH_TYPE
)
ORDER BY B.ID ASC;