SELECT
    SUM(SCORE) SCORE,
    HG.EMP_NO EMP_NO,
    HE.EMP_NAME EMP_NAME,
    HE.POSITION POSITION,
    HE.EMAIL EMAIL
FROM HR_GRADE HG
INNER JOIN HR_EMPLOYEES HE
ON HG.EMP_NO = HE.EMP_NO
INNER JOIN HR_DEPARTMENT HD
ON HD.DEPT_ID = HE.DEPT_ID
WHERE 1 = 1
AND YEAR = 2022
GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;