-- 코드를 입력하세요
SELECT b.BOOK_ID AS BOOK_ID, au.AUTHOR_NAME AS AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b
JOIN AUTHOR au ON b.AUTHOR_ID = au.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC