SELECT he.DEPT_ID DEPT_ID, hd.DEPT_NAME_EN DEPT_NAME_EN, ROUND(AVG(he.SAL), 0) AVG_SAL
FROM HR_EMPLOYEES he
INNER JOIN HR_DEPARTMENT hd
ON he.DEPT_ID = hd.DEPT_ID
GROUP BY he.DEPT_ID
ORDER BY AVG_SAL DESC;