-- 코드를 입력하세요
SELECT crcrh.car_id CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
INNER JOIN (
	SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) c
ON crcrh.CAR_ID = c.CAR_ID
WHERE DATE_FORMAT(crcrh.START_DATE, '%Y-%m') = '2022-10'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
