-- 코드를 입력하세요
SELECT ri.REST_ID REST_ID, ri.REST_NAME REST_NAME, ri.FOOD_TYPE FOOD_TYPE,
	ri.FAVORITES FAVORITES, ri.ADDRESS ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2) SCORE
FROM REST_INFO ri
INNER JOIN REST_REVIEW rr
ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY ri.REST_NAME
ORDER BY SCORE DESC, ri.FAVORITES DESC